DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
sitemap:
  filename: sitemap.xml
languages:
  en:
    # baseUrl: https://digital.canada.ca/
    contentDir: content/en
    lang: en
    languageName: English
    title: CDS Policy Repository
    params: 
      tagline: ""
      githubUrl: "https://github.com/cds-snc/"
      logoSrc: ""
      logoAlt: ""
    Paginate: 6
    frontmatter:
      date: [":filename", ":default"]
    permalinks:
      blog: /:year/:month/:day/:filename
      pages: /:title/
      docs: /:year/:title/
    weight: 1
  fr:
    # baseUrl: https://numerique.canada.ca/
    contentDir: content/fr
    lang: fr
    languageName: Français
    title: "Dépôt de l’équipe politique SNC"
    params: 
      tagline: ""
      githubUrl: "https://github.com/cds-snc/"
      logoSrc: ""
      logoAlt: ""
    Paginate: 6
    weight: 2
    frontmatter:
      date: [":filename", ":default"]
    permalinks:
      blog: /:year/:month/:day/:filename
      pages: /:title/
      docs: /:year/:title/
